// The digital gift templates that were hand-written in the landing page's templates.html, used
// once to fill an empty Template Library (POST /api/templates/import). Videos stay where they
// already are on the landing site; replace any of them from the admin to move it to Supabase.
module.exports = [
  {"name": "Oh My Love", "occasion": "Anniversary", "categories": ["love"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/oh-my-love.mp4"},
  {"name": "All My Love", "occasion": "Anniversary", "categories": ["love"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/all-my-love.mp4"},
  {"name": "My Special One", "occasion": "Anniversary", "categories": ["love"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/my-special-one.mp4"},
  {"name": "Our Love Song", "occasion": "Anniversary", "categories": ["love"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/my-love-song.mp4"},
  {"name": "To My Favorite Graduate", "occasion": "Graduation", "categories": ["celebration"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/to-my-fav-graduate.mp4"},
  {"name": "Congrats BFF", "occasion": "Graduation", "categories": ["celebration"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/congrats-bff.mp4"},
  {"name": "Made Her Smile", "occasion": "Anniversary", "categories": ["birthday"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/made-her-smile.mp4"},
  {"name": "My Graduation Gift", "occasion": "Graduation", "categories": ["celebration"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/my-graduation-gift.mp4"},
  {"name": "Across The Miles", "occasion": "Across The Miles", "categories": ["love"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/across-the-miles.mp4"},
  {"name": "Especially For Her", "occasion": "Anniversary", "categories": ["birthday"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/especially-for-her.mp4"},
  {"name": "Hold My Heart", "occasion": "Anniversary", "categories": ["love"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/hold-my-heart.mp4"},
  {"name": "Gift For You", "occasion": "Anniversary", "categories": ["birthday"], "price": 290, "description": "A soft, romantic love-letter site with a countdown to your next date and a gallery of your favorite moments.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/gift-for-u.mp4"},
  {"name": "My Dad, My Hero", "occasion": "Father's Day", "categories": ["family"], "price": 290, "description": "A playful scrapbook wall of inside jokes, throwback photos, and every \"remember when\" you two have.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/my-dad-my-hero.mp4"},
  {"name": "Happy Mother's Day", "occasion": "Mother's Day", "categories": ["family"], "price": 290, "description": "A playful scrapbook wall of inside jokes, throwback photos, and every \"remember when\" you two have.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/garden-of-gratitude.mp4"},
  {"name": "Beyond BFF", "occasion": "Gift for BFF", "categories": ["birthday", "friendship"], "price": 290, "description": "A playful scrapbook wall of inside jokes, throwback photos, and every \"remember when\" you two have.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/beyond-bff.mp4"},
  {"name": "BFF Birthday", "occasion": "Friendship Anniversary", "categories": ["birthday", "friendship"], "price": 290, "description": "A warm, nostalgic photo-timeline that scrolls through your friendship, year by year, laugh by laugh.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/bff-birthday-yellow.mp4"},
  {"name": "Forever My Mom", "occasion": "Mother's Day", "categories": ["family"], "price": 290, "description": "A warm, nostalgic photo-timeline that scrolls through your friendship, year by year, laugh by laugh.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/forever-my-mom.mp4"},
  {"name": "Thank You Card", "occasion": "Thank You Card", "categories": ["appreciation"], "price": 290, "description": "A warm, nostalgic photo-timeline that scrolls through your friendship, year by year, laugh by laugh.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/thank-you-card.mp4"},
  {"name": "Miss You Card", "occasion": "Miss You Card", "categories": ["appreciation"], "price": 290, "description": "A warm, nostalgic photo-timeline that scrolls through your friendship, year by year, laugh by laugh.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/miss-you-card.mp4"},
  {"name": "I'm Sorry", "occasion": "I'm Sorry", "categories": ["love", "appreciation"], "price": 290, "description": "A warm, nostalgic photo-timeline that scrolls through your friendship, year by year, laugh by laugh.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/i-am-sorry.mp4"},
  {"name": "Our Little Secret", "occasion": "Our Little Secret", "categories": ["love", "appreciation"], "price": 590, "description": "A warm, nostalgic photo-timeline that scrolls through your friendship, year by year, laugh by laugh.", "videoUrl": "https://sochicgifts.vercel.app/videos/templates/our-little-secret.mp4"},
];
